name: Construir APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar código
        uses: actions/checkout@v4

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar Java (Requisito para Android)
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Instalar Flutter (Motor de Android)
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Instalar Flet y librerías
        run: pip install -r requirements.txt

      - name: Fabricar el APK
        run: flet build apk app_movil.py

      - name: Guardar archivo APK
        uses: actions/upload-artifact@v4
        with:
          name: BiblioApp-Movil
          path: build/apk/**/*.apk
